spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/poll'
    username: 'lucas'
    password: '12345678'
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

resource-server: "http://localhost:8081"
web-socket-config:
  endpoint: 'chat'
  cors: '*'