spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: 'lucaspolesello'
    password: 'secret'
  datasource:
    url: 'jdbc:mysql://localhost:3306/poll'
    username: 'lucas'
    password: '12345678'
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

web-socket-config:
  endpoint: '/chat'
  cors: '*'

app:
  environment: "DEVELOPMENT"
  http-server-exec: "http-server -c-1 -p 8081"
  resource-server: "http://localhost:8081"

notification:
  email: 'SEND_EMAIL_QUEUE'