spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/poll'
    username: 'root'
    password: '12345678'
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect